import { type NextPage } from "next";
import Head from "next/head";
import { Box, UnorderedList, ListItem } from "@chakra-ui/react";

type itemType = {
  id: number;
  name: string;
  price: number;
  type: string;
};

type PropType = {
  products: Array<itemType>;
};

const Home: NextPage = (props: PropType) => {
  const { products } = props;
  return (
    <>
      <Head>
        <title>Demo SSR APP</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box>
          <UnorderedList>
            {products.map((product: itemType) => {
              return (
                <ListItem key={product.id}>
                  {product.name} - {product.price}
                </ListItem>
              );
            })}
          </UnorderedList>
        </Box>
      </main>
    </>
  );
};

export async function getStaticProps() {
  return {
    props: {
      // props for your component
      products: [
        {
          id: 1,
          name: "Product 1",
          price: 100,
        },
      ],
    }, // will be passed to the page component as props
  };
}

export default Home;
