import fs from "fs";
import path from "path";

import { type NextPage } from "next";
import Head from "next/head";
import { Box, UnorderedList, ListItem } from "@chakra-ui/react";

type itemType = {
  id: number;
  price: number;
  name: string;
  description: string;
  category: string;
};

type PropType = {
  products: Array<itemType>;
};

const Home: NextPage = (props: PropType) => {
  const { products } = props;
  return (
    <>
      <Head>
        <title>Demo SSR APP</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box>
          <UnorderedList>
            {products.map((product: itemType) => {
              return (
                <ListItem key={product.id}>
                  {product.name} - {product.price} - {product.category} 
                </ListItem>
              );
            })}
          </UnorderedList>
        </Box>
      </main>
    </>
  );
};

export async function getStaticProps() {
  // Call an external API endpoint to get posts.
  // You can use any data fetching library
  const filePath = path.join(process.cwd(), "data", "dummy-backend.json");
  const jsonData = fs.readFileSync(filePath);
  const data: PropType = JSON.parse(jsonData);

  if(!data) {
    return {
      redirect: {
        destination: '/no-data',
        permanent: false,
      },
    }
  }

  if(data.products.length === 0) {
    return {
      notFound: true,
    }
  }

  return {
    props: {
      // props for your component
      products: data.products,
    },
    revalidate: 120 // rerun process to get the latest updates on sertver side
  };
}

export default Home;
